on:
  push:
    branches:
      - main

name: Deploy to Amazon S3 and create Cloudfront invalidations

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        id: build
        env:
          CI: false
        run: |
          echo Build started on `date`
          echo Install dependencies
          npm i
          echo Build
          npm run build
          echo Build completed on `date`

      - name: Upload
        id: upload
        run: |
          echo Build completed on `date`
          echo Uploading s3
          cd build
          aws s3 sync --delete . ${{ secrets.SULTANS_HOMEPAGE_AWS_BUCKET }}

      - name: Invalidate Cache
        id: invalidate_cache
        run: |
          echo Invalidating cache
          aws cloudfront create-invalidation --distribution-id ${{ secrets.SULTANS_HOMEPAGE_AWS_CLOUDFRONT_ID }} --paths "/*"
